### ISSUE TITLE
Add static page

### ISSUE THREAD

**Issue by Sakshat682** [Sakshat682/htmlcss#7]
Add a html page which makes the intro for our website

**Comment by SJ682** [comment]
I want to work with this issue, how to start?

**Comment by Sakshat682** [comment]
Just apply basic bootstrap with beautiful colors and write some lines about our project and about our team. You can get the information inside the readme file.

**Comment by SJ682** [comment]
Ok I understood, please assign the issue to me.

**Comment by Sakshat682** [comment]
Issue is now solved, thnx SJ682
